name: Hotfix Pipeline

on:
  push:
    branches:
      - hotfix/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Build"

  tf-plan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: TF Plan
        run: echo "TF Plan"

  approval-before-apply:
    runs-on: ubuntu-latest
    needs: tf-plan
    environment:
      name: approval-before-apply
    steps:
      - name: Approval Gate Before TF Apply
        run: echo "Gated Approval (Before Apply)"

  tf-apply:
    runs-on: ubuntu-latest
    needs: approval-before-apply
    steps:
      - name: TF Apply (PRD)
        run: echo "TF Apply (PRD)"

  approval-before-deploy:
    runs-on: ubuntu-latest
    needs: tf-apply
    environment:
      name: approval-before-deploy
    steps:
      - name: Approval Gate Before Deploy
        run: echo "Gated Approval (Before Deploy)"

  deploy-app:
    runs-on: ubuntu-latest
    needs: approval-before-deploy
    steps:
      - name: Deploy App (PRD)
        run: echo "Deploy App (PRD)"
