name: Full Pipeline

on:
  workflow_dispatch:   # Manual trigger

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Unit Test
        run: echo "Unit test"
      - name: Style Checking
        run: echo "Style Checking"
      - name: Code Quality
        run: echo "Code Quality"
      - name: Code Scanning
        run: echo "Code Scanning"

  Build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Build
        run: echo "Build"

  Plan:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Terraform Plan
        run: echo "TF Plan"

  Deploy_DEV:
    runs-on: ubuntu-latest
    needs: Plan
    steps:
      - name: Terraform Apply (Dev)
        run: echo "TF Apply (Dev)"
      - name: Deploy App (Dev)
        run: echo "Deploy App (Dev)"

  Service_Testing:
    runs-on: ubuntu-latest
    needs: Deploy_DEV
    steps:
      - name: Service Testing
        run: echo "Service Testing"

  Approval:
    runs-on: ubuntu-latest
    needs: Service_Testing
    environment: qa-approval   # This enables a manual approval in GitHub
    steps:
      - name: Waiting for QA Approval
        run: echo "QA Approval Granted"

  Deploy_QA:
    runs-on: ubuntu-latest
    needs: Approval
    steps:
      - name: Terraform Apply (QA)
        run: echo "TF Apply (QA)"
      - name: Deploy App (QA)
        run: echo "Deploy App (QA)"

  System_Testing:
    runs-on: ubuntu-latest
    needs: Deploy_QA
    steps:
      - name: System Testing
        run: echo "System Testing"

  Deploy_PRD:
    runs-on: ubunutu-latest
    steps:
      - name: Gated Approval
        run: echo "Gate Approval"
      - name: TF Apply (PRD)
        run: echo "TF Apply"
      - name: Gatted Approval
        run: echo "Gate Approval"
      - name: Deploy App (PRD)
        run: echo "Deploy Production"
        
